sudo: required
dist: xenial

addons:
  apt:
    packages:
      - postgresql-12
      - postgresql-12-postgis-3
      - postgresql-12-postgis-3-scripts
      - postgis
  postgresql: '12'

env:
    global:
        - PGVER=12
        - PGPORT=5433

services:
  - postgresql

script:
#  - find / -name shp2pgsql* 2>/dev/null 
  - echo "select version()" | psql template1
  - make check RUNTESTFLAGS=-v

